name: build_and_test
on: [push, pull_request]
jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: foxy
      - name: build_and_test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name: |
            rmf_traffic_ros2 |
            rmf_task_ros2 |
            rmf_fleet_adapter |
            rmf_fleet_adapter_python
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_C_FLAGS='--coverage -fsanitize=thread -O2 -g -fno-omit-frame-pointer'",
                  "-DCMAKE_CXX_FLAGS='--coverage -fsanitize=thread -O2 -g -fno-omit-frame-pointer'"
                ]
              }
            }
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ros_ws/lcov/total_coverage.info
          flags: tests
          name: lean_and_mean_codecov_bot
