name: tsan
on: 
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-20.04
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - name: cyclone
        run: |
          sudo apt update
          sudo apt install ros-foxy-rmw-cyclonedds-cpp -y
      - name: tsan_build_test
        uses: ros-tooling/action-ros-ci@v0.2
        id: tsan_build_test
        env:
          CC: clang
          CXX: clang++
          RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name: |
            rmf_traffic_ros2
            rmf_task_ros2
            rmf_fleet_adapter
            rmf_fleet_adapter_python
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["tsan"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Debug"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: upload_test_stream
        uses: actions/upload-artifact@v2
        with:
          name: colcon-test-logs
          path: |
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_traffic_ros2/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_task_ros2/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_fleet_adapter/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_fleet_adapter_python/streams.log
        if: always()
